### ISSUE TITLE
replaceRegister not working on LimeSurvey 2.64.3+170327

### ISSUE THREAD

**Issue by gassius** [Shnoulle/LS-replaceRegister#1]
Hi Dennis

I wonder if this plugin is active and working on LimeSurvey version 2.64.3+170327 because I installed it, activated it and confirmed in the settings page for the survey, but still after registration I get the confirmation screen. I want to skip directly to the survey. I am missing something? 

Regards

**Comment by Shnoulle** [comment]
It's not the purpose of this survey. Currently : some system included in this survey is already in new LS version.

see https://github.com/SondagesPro/LS-registerQuick
